name: Godot CI Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GODOT_VERSION: "4.8-dev5"
  GODOT_DOT_VERSION: "4.8.dev5"

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64
            preset: Linux-x86_64
            output_dir: build/linux-x86_64
            output_file: gd-asm_linux-x86_64.x86_64

          - name: linux-arm64
            preset: Linux-arm64
            output_dir: build/linux-arm64
            output_file: gd-asm_linux-arm64

          - name: windows
            preset: Windows
            output_dir: build/windows
            output_file: gd-asm_windows.exe

          - name: macos
            preset: Macos
            output_dir: build/macos
            output_file: GD-ASM.app
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Godot
        run: |
          wget "https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_linux.x86_64.zip"
          unzip "Godot_v${GODOT_VERSION}_linux.x86_64.zip"
          sudo mv "Godot_v${GODOT_VERSION}_linux.x86_64" /usr/local/bin/godot
          godot --version
      
      - name: Install Export Templates
        run: |
          wget "https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz"
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_DOT_VERSION}
          unzip "Godot_v${GODOT_VERSION}_export_templates.tpz" -d ~/.local/share/godot/export_templates/${GODOT_DOT_VERSION}
          mv ~/.local/share/godot/export_templates/${GODOT_DOT_VERSION}/templates/* ~/.local/share/godot/export_templates/${GODOT_DOT_VERSION}/
          rm -rf ~/.local/share/godot/export_templates/${GODOT_DOT_VERSION}/templates

      - name: Export
        run: |
          rm -rf "${{ matrix.output_dir }}"
          mkdir -p "${{ matrix.output_dir }}"

          godot --headless --verbose \
            --path "$GITHUB_WORKSPACE" \
            --export-release "${{ matrix.preset }}" \
            "$GITHUB_WORKSPACE/${{ matrix.output_dir }}/${{ matrix.output_file }}"
      
      - name: Package
        run: |
          mkdir -p artifacts

          cd "${{ matrix.output_dir }}"

          zip -r \
            "$GITHUB_WORKSPACE/artifacts/gd-asm_${{ matrix.name }}.zip" \
            .
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: artifacts/${{ matrix.name }}.zip
          retention-days: 30